### ISSUE TITLE
https://beenje.github.io/ redirect to your blog, but not here

### ISSUE THREAD

**Issue by username7171** [beenje/beenje.github.io#1]
Are you using DNS to route https://beenje.github.io/ to elsewhere?  Your repo contains nothing but the blog is great.

**Comment by beenje** [comment]
The source of the blog is here: https://github.com/beenje/blog/tree/master

I'm using GitHub pages: https://pages.github.com
This empty repo is needed for that.

**Comment by beenje** [comment]
Note that I'm using [Nikola](https://getnikola.com) to generate the blog. You can see that in the source I mentioned above if you are interested.
